name: ⛔️ Bug Report
description: Report a new bug
title: ""
labels: [bug]
body:
- type: textarea
  attributes:
    label: Description
    description: Provide a concise description of the problem
  validations:
    required: true
- type: textarea
  attributes:
    label: Current Behavior
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: How can the bug be reproduced? 
    placeholder: |
      1. Go to ...
      2. Click on ...
      3. See Error
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      Provide any environment information you might find useful
    value: |
        - OS: macOS Monterey v12.5
        - VS Code: v1.69.2
        - Java: JDK 11
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional Information
    description: |
      Provide additional information that might be useful (screenshots, logfiles, model file)
  validations:
    required: false
